//! `.lean-ctx/lean-md.lock` — seed provenance.
//!
//! `materialize_contracts` can only see "local != embedded" and cannot tell a user
//! edit from a seed that moved on. The lock preserves the *historical* seed hash —
//! the one a newer binary no longer carries. No hash, no provenance.
//!
//! Format is coreutils `sha256sum`, not TOML: the semantics of `sha256sum -c`
//! *are* the provenance question, so the user can answer it without trusting us.
//! Paths are relative to `.lean-ctx/`, i.e. the directory `sha256sum -c` runs in.

use std::path::{Path, PathBuf};

/// Lock location, relative to the project root.
pub const LOCK_REL: &str = ".lean-ctx/lean-md.lock";

/// Recorded seed hashes: (path relative to `.lean-ctx/`, lowercase hex digest).
#[derive(Default)]
pub struct Lock {
    entries: Vec<(String, String)>,
}

impl Lock {
    /// Reads the lock; an absent or unreadable lock is an empty lock, never an error.
    pub fn load(project_root: &Path) -> Lock {
        let mut lock = Lock::default();
        let Ok(raw) = std::fs::read_to_string(Self::path(project_root)) else {
            return lock;
        };
        for line in raw.lines() {
            let line = line.trim_end();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if let Some((hex, rel)) = line.split_once("  ") {
                lock.set(rel, hex);
            }
        }
        lock
    }

    pub fn get(&self, rel: &str) -> Option<&str> {
        self.entries
            .iter()
            .find(|(p, _)| p == rel)
            .map(|(_, h)| h.as_str())
    }

    pub fn set(&mut self, rel: &str, hex: &str) {
        match self.entries.iter_mut().find(|(p, _)| p == rel) {
            Some(e) => e.1 = hex.to_string(),
            None => self.entries.push((rel.to_string(), hex.to_string())),
        }
    }

    /// `sha256sum` rendering. Entries are sorted by path so the bytes are a
    /// function of the content alone (#498), not of insertion order.
    pub fn render(&self) -> String {
        let mut sorted = self.entries.clone();
        sorted.sort();
        let mut out = String::from(
            "# lean-md.lock — generated by lean-md; commit this file.\n\
             # binary_version: ",
        );
        out.push_str(env!("CARGO_PKG_VERSION"));
        out.push_str("\n# Eigene Anpassungen prüfen:  cd .lean-ctx && sha256sum -c lean-md.lock\n");
        for (rel, hex) in &sorted {
            out.push_str(&format!("{hex}  {rel}\n"));
        }
        out
    }

    pub fn save(&self, project_root: &Path) -> std::io::Result<()> {
        let path = Self::path(project_root);
        if let Some(dir) = path.parent() {
            std::fs::create_dir_all(dir)?;
        }
        std::fs::write(path, self.render())
    }

    fn path(project_root: &Path) -> PathBuf {
        project_root.join(LOCK_REL)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lock_is_checkable_by_coreutils_sha256sum() {
        // The whole reason SHA-256 was chosen over a dep-free hash: the user must be able
        // to re-check every value with a standard command. If coreutils cannot read our
        // file, the format has failed its only job. Also verifies the spec's unverified
        // assumption that `#` lines are ignored by --check.
        let root = std::env::temp_dir().join(format!("lmd_lock_c14n_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        let dir = root.join(".lean-ctx/lean-md");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("probe.lmd.md"), "probe content\n").unwrap();

        let mut lock = Lock::load(&root);
        lock.set(
            "lean-md/probe.lmd.md",
            &crate::hashx::sha256_hex(b"probe content\n"),
        );
        lock.save(&root).unwrap();

        let out = std::process::Command::new("sha256sum")
            .arg("-c")
            .arg("lean-md.lock")
            .current_dir(root.join(".lean-ctx"))
            .output();
        let Ok(out) = out else {
            eprintln!("sha256sum unavailable — skipping coreutils cross-check");
            let _ = std::fs::remove_dir_all(&root);
            return;
        };
        assert!(
            out.status.success(),
            "coreutils rejected our lock: {}{}",
            String::from_utf8_lossy(&out.stdout),
            String::from_utf8_lossy(&out.stderr)
        );

        // An edited seed must read as FAILED — that is the provenance question itself.
        std::fs::write(dir.join("probe.lmd.md"), "user edit\n").unwrap();
        let out = std::process::Command::new("sha256sum")
            .arg("-c")
            .arg("lean-md.lock")
            .current_dir(root.join(".lean-ctx"))
            .output()
            .unwrap();
        assert!(!out.status.success(), "edited seed must fail sha256sum -c");

        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn absent_lock_loads_empty_and_is_not_an_error() {
        let root = std::env::temp_dir().join(format!("lmd_lock_absent_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        let lock = Lock::load(&root);
        assert_eq!(lock.get("lean-md/lang/rust.lmd.md"), None);
    }

    #[test]
    fn lock_round_trips_and_paths_are_relative_to_lean_ctx() {
        let root = std::env::temp_dir().join(format!("lmd_lock_rt_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(root.join(".lean-ctx")).unwrap();
        let mut lock = Lock::load(&root);
        lock.set("lean-md/lang/rust.lmd.md", "deadbeef");
        lock.save(&root).unwrap();

        let raw = std::fs::read_to_string(root.join(".lean-ctx/lean-md.lock")).unwrap();
        assert!(
            raw.contains("deadbeef  lean-md/lang/rust.lmd.md"),
            "sha256sum format (two spaces), path relative to .lean-ctx: {raw}"
        );
        assert!(
            raw.contains("# binary_version: "),
            "binary_version comment missing"
        );
        assert!(
            !raw.contains(".lean-ctx/lean-md/lang"),
            "paths must NOT be relative to project_root — sha256sum -c runs in .lean-ctx"
        );
        assert_eq!(
            Lock::load(&root).get("lean-md/lang/rust.lmd.md"),
            Some("deadbeef")
        );
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn lock_render_is_byte_stable() {
        // #498: same entries → same bytes, regardless of insertion order.
        let mut a = Lock::default();
        a.set("lean-md/b.lmd.md", "22");
        a.set("lean-md/a.lmd.md", "11");
        let mut b = Lock::default();
        b.set("lean-md/a.lmd.md", "11");
        b.set("lean-md/b.lmd.md", "22");
        assert_eq!(a.render(), b.render());
    }
}
