//! Skill-body variables config (Spec: @var). Three skill-agnostic primitives:
//! `load_vars` (jailed vars.toml → override map), `scan_var_decls` (full body →
//! declarations), `render_vars_template` (declarations → commented vars.toml).
//! Hermetic; no `toml` dependency (flat `key = "value"` subset parsed by hand).

use std::collections::HashMap;
use std::path::Path;

/// A `@var NAME default="…" [desc="…"]` declaration scanned from a skill body.
#[derive(Debug, Clone, PartialEq)]
pub struct VarDecl {
    pub name: String,
    pub default: String,
    pub desc: Option<String>,
}

/// Load `<jail_root>/.lean-ctx/lean-md/vars.toml` (jailed) into an override map.
/// Absent / un-jailed (`..`/symlink escape) / unreadable → empty map (no error,
/// the common case). Flat `key = "value"` subset only.
pub fn load_vars(jail_root: &Path) -> HashMap<String, String> {
    let candidate = jail_root.join(".lean-ctx/lean-md/vars.toml");
    let Ok(resolved) = crate::pathx::jail_path(&candidate, jail_root) else {
        return HashMap::new();
    };
    let Ok(text) = std::fs::read_to_string(&resolved) else {
        return HashMap::new();
    };
    parse_vars_toml(&text)
}

/// Parse the flat `key = "value"` TOML subset. Best-effort: `#` comments and
/// blank lines are ignored; a line without a quoted string value is skipped.
fn parse_vars_toml(text: &str) -> HashMap<String, String> {
    let mut map = HashMap::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((key, rest)) = line.split_once('=') else {
            continue;
        };
        let key = key.trim();
        let rest = rest.trim();
        // Value must be a double-quoted string (>= 2 chars: the two quotes).
        if key.is_empty() || rest.len() < 2 || !rest.starts_with('"') || !rest.ends_with('"') {
            continue;
        }
        let val = &rest[1..rest.len() - 1];
        map.insert(key.to_string(), val.to_string());
    }
    map
}

/// Extract every `@var NAME default="…" [desc="…"]` block declaration from the
/// FULL body (one source, two users: render pre-pass + `vars --init`). A bare
/// `@var NAME` (no `default=`) is a lookup, not a declaration, and is skipped.
pub fn scan_var_decls(body: &str) -> Vec<VarDecl> {
    let mut out = Vec::new();
    for line in body.lines() {
        let Some(rest) = line.trim_start().strip_prefix("@var ") else {
            continue;
        };
        let args = crate::args::DirectiveArgs::parse(rest);
        let (Some(default), Some(name)) = (args.get("default"), args.positional(0)) else {
            continue;
        };
        out.push(VarDecl {
            name: name.to_string(),
            default: default.to_string(),
            desc: args.get("desc").map(str::to_string),
        });
    }
    out
}

/// Render a commented `vars.toml` from declarations. Dedup by name (first wins);
/// a divergent later default emits a `# WARN:` line (transparent, no silent
/// overwrite). Same name + same default → one silent entry.
pub fn render_vars_template(decls: &[VarDecl]) -> String {
    let mut out = String::from(
        "# lmd skill vars — generated by `lean-md skill vars --init`\n\
         # Edit values; renders pull them automatically (precedence: this file > seed default).\n",
    );
    let mut seen: HashMap<String, String> = HashMap::new();
    for d in decls {
        if let Some(first) = seen.get(&d.name) {
            if first != &d.default {
                out.push_str(&format!(
                    "# WARN: {} has divergent defaults across skills (kept \"{}\", ignored \"{}\")\n",
                    d.name, first, d.default
                ));
            }
            continue;
        }
        seen.insert(d.name.clone(), d.default.clone());
        out.push('\n');
        if let Some(desc) = &d.desc {
            out.push_str(&format!("# {}: {}\n", d.name, desc));
        }
        out.push_str(&format!("{} = \"{}\"\n", d.name, d.default));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn load_vars_reads_jailed_toml() {
        let root = std::env::temp_dir().join(format!("lmd_vars_load_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        let dir = root.join(".lean-ctx/lean-md");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("vars.toml"), "test_cmd = \"cargo nextest run\"\n").unwrap();
        let map = load_vars(&root);
        assert_eq!(
            map.get("test_cmd").map(String::as_str),
            Some("cargo nextest run")
        );
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn load_vars_absent_is_empty() {
        let root = std::env::temp_dir().join(format!("lmd_vars_absent_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).unwrap();
        assert!(load_vars(&root).is_empty());
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn parse_handles_comments_blanks_and_bad_lines() {
        let text = "# header comment\n\ngood = \"value\"\nbad line no equals\nflag = bare\n";
        let map = parse_vars_toml(text);
        assert_eq!(map.get("good").map(String::as_str), Some("value"));
        assert!(!map.contains_key("bad"));
        assert!(!map.contains_key("flag")); // unquoted value skipped
        assert_eq!(map.len(), 1);
    }

    #[test]
    fn scan_extracts_name_default_desc() {
        let body = "<!-- comment -->\n@var test_cmd default=\"cargo test\" desc=\"runner\"\n@phase \"red\"\nuse {{ var test_cmd }}\n@phase-end\n";
        let decls = scan_var_decls(body);
        assert_eq!(decls.len(), 1);
        assert_eq!(
            decls[0],
            VarDecl {
                name: "test_cmd".to_string(),
                default: "cargo test".to_string(),
                desc: Some("runner".to_string()),
            }
        );
    }

    #[test]
    fn scan_ignores_bare_lookup_lines() {
        // A line without `default=` is a lookup, not a declaration.
        let body = "@var test_cmd\n";
        assert!(scan_var_decls(body).is_empty());
    }

    #[test]
    fn render_template_emits_desc_and_default() {
        let decls = vec![VarDecl {
            name: "test_cmd".to_string(),
            default: "cargo test".to_string(),
            desc: Some("runner".to_string()),
        }];
        let out = render_vars_template(&decls);
        assert!(out.contains("# test_cmd: runner"), "desc comment: {out}");
        assert!(
            out.contains("test_cmd = \"cargo test\""),
            "assignment: {out}"
        );
    }

    #[test]
    fn render_template_divergent_defaults_warn_single_entry() {
        let decls = vec![
            VarDecl {
                name: "test_cmd".to_string(),
                default: "cargo test".to_string(),
                desc: None,
            },
            VarDecl {
                name: "test_cmd".to_string(),
                default: "cargo nextest run".to_string(),
                desc: None,
            },
        ];
        let out = render_vars_template(&decls);
        assert!(out.contains("# WARN: test_cmd"), "divergence warn: {out}");
        assert_eq!(
            out.matches("test_cmd = ").count(),
            1,
            "exactly one entry: {out}"
        );
    }

    #[test]
    fn render_template_same_default_dedups_silently() {
        let decls = vec![
            VarDecl {
                name: "test_cmd".to_string(),
                default: "cargo test".to_string(),
                desc: None,
            },
            VarDecl {
                name: "test_cmd".to_string(),
                default: "cargo test".to_string(),
                desc: None,
            },
        ];
        let out = render_vars_template(&decls);
        assert!(
            !out.contains("# WARN:"),
            "no warn for identical default: {out}"
        );
        assert_eq!(out.matches("test_cmd = ").count(), 1);
    }
}
